version: 2.1

jobs:
    test_auto_apply_migrations:
        docker:
            - image: circleci/node
            - image: postgres:12
              name: postgres
              environment:
                POSTGRES_PASSWORD: postgrespassword
            - image: hasura/graphql-engine:v1.3.2.cli-migrations-v2
              name: hasura
              command: ["sh", "-c", "sleep 30 && graphql-engine serve && hasura-cli migrate apply --endpoint http://hasura:8080 && hasura-cli metadata apply --endpoint http://hasura:8080 && hasura-cli seed apply --endpoint http://hasura:8080"]
              environment: 
                HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
                HASURA_GRAPHQL_ADMIN_SECRET: key
        steps:
            - checkout
            - run:
                name: Wait for Hasura
                command: dockerize -wait tcp://hasura:8080 -timeout 1m


workflows:
  version: 2

  test:
    jobs:
      - test_auto_apply_migrations
