version: 2.1

orbs:
    mount-hasura:
      orbs:
        docker: circleci/docker@1.5.0
      commands:
        mount-hasura:
          steps:
            - checkout
            - run: 
                name: Mount the containers
                command: docker-compose up -d
            - run:
                name: Wait for Hasura
                command: dockerize -wait tcp://hasura:8080 -timeout 1m
      jobs:
        test_auto_apply_migrations:
            docker:
                - image: circleci/node
            steps:
                - checkout
                # - run:
                #     name: up the hasura env
                #     command: docker-compose up -d
                - mount-hasura
                - run:
                    name: Wait for Hasura
                    command: dockerize -wait tcp://hasura:8080 -timeout 1m
                # - run:
                #     name: install cli
                #     command: curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash
                # - run:
                #     name: run migrations
                #     command: hasura migrate apply
                # - run:
                #     name: run metadatas
                #     command: hasura metadata apply 
                # - run:
                #     name: run migrations
                #     command: hasura seed apply

workflows:
  test:
    jobs:
      - mount-hasura/test_auto_apply_migrations
