version: 2.1

orbs:
  cypress: cypress-io/cypress@1

executors:
  node:
    docker:
      - image: circleci/node
  hasura:
    docker:
      - image: circleci/node
      - image: postgres:12
        name: postgres
        environment:
          POSTGRES_PASSWORD: postgrespassword
      - image: hasura/graphql-engine:v1.3.2.cli-migrations-v2
        name: hasura
        environment:
          HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
          HASURA_GRAPHQL_ADMIN_SECRET: key
  docker:
    docker:
      - image: docker:stable

jobs:
  hasura-test-apply-migrations:
    executor: hasura
    steps:
      - checkout
      - run:
          name: "install hasura cli"
          command: sudo npm i -g hasura-cli
      - run:
          name: "wait for Hasura for a minute max"
          command: dockerize -wait tcp://hasura:8080 -timeout 1m
      - run:
          name: migrate
          working_directory: hasura
          command: hasura migrate apply --endpoint http://hasura:8080
      - run:
          name: metadata
          working_directory: hasura
          command: hasura metadata apply --endpoint http://hasura:8080
      - run:
          name: seeds
          working_directory: hasura
          command: hasura seeds apply --endpoint http://hasura:8080
  install-dependencies:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-packaging-dependencies-{{ checksum "package-lock.json" }}
            - v3-packaging-dependencies-
      - run:
          name: install-dependencies
          command: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v3-packaging-dependencies-{{ checksum "package-lock.json" }}
  qc-prettier:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-packaging-dependencies-{{ checksum "package-lock.json" }}
            - v3-packaging-dependencies-
      - run:
          name: qc-prettier
          command: npm run prettier:check
  build:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-packaging-dependencies-{{ checksum "package-lock.json" }}
            - v3-packaging-dependencies-
      - run:
          name: build
          command: npm run build
  unit-test:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-packaging-dependencies-{{ checksum "package-lock.json" }}
            - v3-packaging-dependencies-
      - run:
          name: unit-test
          command: npm run test:unit

workflows:
  qc-test-deploy:
    jobs:
      - hasura-test-apply-migrations
      - install-dependencies
      - qc-prettier:
          requires:
            - install-dependencies
      - build:
          requires:
            - install-dependencies
      - unit-test:
          requires:
            - install-dependencies
      - cypress/install:
          cache-key: >-
            v3-packaging-dependencies-cypress-{{ checksum "package-lock.json" }}
      - cypress/run:
          name: chrome-cypress-run
          requires:
            - cypress/install
          cache-key: >-
            v3-packaging-dependencies-cypress-{{ checksum "package-lock.json" }}
          start: npm run dev
          wait-on: "http://localhost:3000"
          executor: cypress/browsers-chrome78-ff70
          browser: chrome
          parallel: true
          parallelism: 2
      - cypress/run:
          name: firefox-cypress-run
          requires:
            - cypress/install
          cache-key: >-
            v3-packaging-dependencies-cypress-{{ checksum "package-lock.json" }}
          start: npm run dev
          wait-on: "http://localhost:3000"
          executor: cypress/browsers-chrome78-ff70
          browser: firefox
          parallel: true
          parallelism: 2
